services:
  - type: web
    name: fantacalcio-pro
    env: node
    plan: free
    buildCommand: npm run build-all
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
